
title: heliumenabler
email: contact@heliumenabler.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is dedicated to all helium fans and miners. Other than sharing ideas among helium miners on the dos and donts, pitfalls and successes, we also like to explore projects that utilizes helium and its benefits. Please feel free to send us inputs on what you'll like covered and we will try our best to accomodate. Have a wonderful day and thank you for visiting us.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: heliumenabler
github_username:  heliumenabler

# Build settings
future: true
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
